# docker container run --name db --rm -p 5432:5432 -v /home/adriano-fonseca/docker/docker-postgres/postgresql/:/var/lib/postgresql -e DB_USER=app -e DB_PASS=app -e DB_NAME=app sameersbn/postgresql:9.5-3
PostgreSQL:
  #restart: always
  image: adrianofonseca/postgres:9.5 
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=app
    - DB_PASS=app
    - DB_NAME=app
    - DB_TEMPLATE=
    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=
  volumes:
    - ./postgresql:/var/lib/postgresql
